### ISSUE TITLE
Waiting for Part-8 Event Driven Microservices using Kafka

### ISSUE THREAD

**Issue by soumya-ranjan7** [SaiUpadhyayula/spring-boot-microservices-new#1]
Hey! Could you please provide an update on when can we expect the next part to come out?

**Comment by SaiUpadhyayula** [comment]
It's out now :)

**Comment by soumya-ranjan7** [comment]
Yes, viewed it today. Got to learn a lot about Kafka. Waiting for next videos on the series!
