### ISSUE TITLE
Deprecated WebSecurityConfigurerAdapter - KeyCloak section

### ISSUE THREAD

**Issue by ntn0de** [SaiUpadhyayula/spring-boot-microservices-new#4]
Having trouble signing in on eureka web. Seems like they have deprecated WebSecurityConfigurerAdapter
 https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter

**Comment by iangithua** [comment]
Change the application properties from 

app.eureka.username=eureka
app.eureka.password=password

To 

spring.security.user.name=eureka
spring.security.user.password=password

**Comment by andyholes** [comment]
Check your user and password @Value properties, they are lacking a curly brace!

**Comment by SaiUpadhyayula** [comment]
> Check your user and password @value properties, they are lacking a curly brace!

The repository will soon be updated with latest Spring Boot & Spring Security Changes, the above comment answers the question regarding the problem with login

**Comment by ntn0de** [comment]
Thanks @andyholes , Such a silly ignorance by me. 
Thanks @iangithua for the input.
Thanks @SaiUpadhyayula for the great tutorial, looking forward to more from you!!
